version: '3.8'

services:
  fyp-api:
    image: ghcr.io/dylangore-fyp/api:latest
    container_name: fyp_api
    build:
      context: .
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5000:5000
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
