version: '3.8'

services:
  fyp-api:
    image: ghcr.io/dylangore-fyp/api:latest
    container_name: fyp_api
    build:
      context: .
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5000:5000
    security_opt:
      - no-new-privileges:true
    environment:
      INFLUX_HOST: 127.0.0.1
      INFLUX_PORT: 8086
      INFLUX_TOKEN: MyToken
      INFLUX_ORG: MyOrg
      INFLUX_BUCKET: MyBucket
      ENABLE_METRICS: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./serviceAccountKey.json:/fyp-api/serviceAccountKey.json
